#!/bin/bash

cd `dirname $0`

readonly MAPNIK_VT_PATH=${MAPNIK_VT_PATH:-/mapnik-vector-tile}

cat > mapnik_config.go <<EOF
package mapnik

// THIS FILE IS AUTO GENERATED BY go generate !DO NOT EDIT!

// #cgo CXXFLAGS: $(mapnik-config --cxxflags) $(mapnik-config --cflags) -I$MAPNIK_VT_PATH/deps/protozero/include -I$MAPNIK_VT_PATH/build/Release/obj/gen -I$MAPNIK_VT_PATH/src -I/usr/local/lib/protozero/include -I/usr/local/opt/icu4c/include
// #cgo CFLAGS: -I$MAPNIK_VT_PATH/deps -I$MAPNIK_VT_PATH/build/Release/obj/gen -I$MAPNIK_VT_PATH/src -I/usr/local/lib/protozero/include -I/usr/local/opt/icu4c/include
// #cgo LDFLAGS: $(mapnik-config --libs) -lboost_system -lprotobuf -L/usr/local/opt/icu4c/lib -licuuc
import "C"

const (
	fontPath   = "$(mapnik-config --fonts)"
	pluginPath = "$(mapnik-config --input-plugins)"
)
EOF

